In [6]:
import re
import pandas as pd

In [7]:
f=open("WhatsApp Chat - RMC' 24 Official Members .txt","r",encoding="utf-8")

In [8]:
data=f.read()

In [9]:
print(data)

5/26/24, 9:06 AM - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
5/25/24, 10:10 PM - Sayal Singh Sikarwar Bhaiya RMC created group "RMC' 24 Official Members "
5/26/24, 9:06 AM - You joined a group via invite in the community: RMC'24 Official
5/26/24, 11:04 AM - +91 78773 95130 joined using this group's invite link
5/26/24, 4:14 PM - Rohan Kaari Room No. 506 joined using this group's invite link
5/26/24, 6:49 PM - Sayal Singh Sikarwar Bhaiya RMC added Abhradeep Paari 402
6/22/24, 2:54 PM - Anjul Kaari Room No. 506: 🛑🛑🛑:-NOTICE-:🛑🛑🛑

Subject: Mandatory Club Meeting – Next Saturday at 10 PM

Hello everyone,

I hope this message finds you well.

This is to inform you that we will be holding a mandatory club meeting next Saturday at 10 PM. Your presence is compulsory, as we will be discussing important matters related to the upcoming tenure of the club.

Meeting Details:
**Date:** 29 JUNE
**Time:** 10 PM
**Venue:** Online

The agenda will include key topics and decisions that will shape our activities and plans for the next tenure. Your input and participation are crucial to ensure we have a successful and productive period ahead.

Please mark your calendars and make the necessary arrangements to attend this important meeting. If you have any questions or need further information, do not hesitate to reach out.

Looking forward to seeing you all there.

Kindly acknowledge this message.

Regards,
6/24/24, 7:32 PM - Anjul Kaari Room No. 506 pinned a message
6/29/24, 11:46 AM - Sayal Singh Sikarwar Bhaiya RMC: *REMINDER* 🟥🟥🟥
6/29/24, 1:18 PM - Sayal Singh Sikarwar Bhaiya RMC: Kindly Pay Attention
The meeting that was going to happen today has been shifted to tomorrow ( Sunday 30 June 2024) ,timing will be  9 p.m.

Thank you
6/29/24, 1:19 PM - Sayal Singh Sikarwar Bhaiya RMC: Kindly react @120363283633300637@g.us
6/30/24, 8:32 PM - Sayal Singh Sikarwar Bhaiya RMC: Reminder 🟥🟥
6/30/24, 8:57 PM - Anjul Kaari Room No. 506: https://meet.google.com/obc-kdda-acq
6/30/24, 8:58 PM - Anjul Kaari Room No. 506: Guys Join this meet on sharp 9:00
6/30/24, 9:02 PM - Sayal Singh Sikarwar Bhaiya RMC added Satvik Sawhney Bhaiya RMC
6/30/24, 10:45 PM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
7/8/24, 12:53 PM - Sayal Singh Sikarwar Bhaiya RMC: All the board members today we are going to have an online meet by 9 pm. It's not a request. Everyone has to join , we are right now in a tough situation.
7/8/24, 12:53 PM - Sayal Singh Sikarwar Bhaiya RMC: @120363283633300637@g.us
7/8/24, 12:53 PM - Sayal Singh Sikarwar Bhaiya RMC: Everyone has to react to this message
7/8/24, 12:53 PM - Sayal Singh Sikarwar Bhaiya RMC: Time can change 1 hr prior or 1 hr late so be prepared
7/8/24, 12:53 PM - Sayal Singh Sikarwar Bhaiya RMC: And it's a serious thing
7/8/24, 12:54 PM - Sayal Singh Sikarwar Bhaiya RMC: If there is ANYTHING why u can't join the meet tell now and please don't consider this as an excuse
7/8/24, 12:54 PM - Sayal Singh Sikarwar Bhaiya RMC: Especially call-out to @918885450457  u have missed the last meet also without any specific reason
7/8/24, 9:47 PM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
7/28/24, 7:23 AM - +91 90070 58128: 🛑🛑🛑:-NOTICE-:🛑🛑🛑

Subject: Mandatory Offline Meeting – 30/07/2024 at 5 PM

Hi everyone,

This is to inform you that an offline club meeting will be held on 30th July at 5 PM. Your presence is mandatory, as we will be discussing important matters related to the upcoming tenure of the club.

Meeting Details:
**Date:** 30 JULY
**Time:** 5 PM
**Venue:** In front of Architecture building

React to this message once you receive it.

Thank you!
7/30/24, 11:14 AM - Sayal Singh Sikarwar Bhaiya RMC: Reminder 🟥🟥🟥
7/30/24, 4:59 PM - Sayal Singh Sikarwar Bhaiya RMC: Everyone come fast
8/2/24, 6:43 PM - Akshada Didi RMC Vice - Secretary changed this group's settings to allow all members to send messages to this group
8/2/24, 6:43 PM - Akshada Didi RMC Vice - Secretary changed this group's settings to allow only admins to send messages to this group
8/2/24, 6:43 PM - Akshada Didi RMC Vice - Secretary changed this group's settings to allow all members to send messages to this group
8/2/24, 6:41 PM - Akshada Didi RMC Vice - Secretary: good evening, everyone 🙏🏼

alongside starting our prep for IMF'24, we should start focusing on growing our Instagram acc too, and so I'm hoping we start a discussion on the same here

pls post your ideas on how to do the same: reel ideas, engaging posts/stories, etc.

hoping for everyone to respond 👾
8/2/24, 6:42 PM - Akshada Didi RMC Vice - Secretary: I was thinking we gather ideas on integrating mathematics w memes, and make reels that way

post 2-3 per week
8/8/24, 2:40 PM - Sayal Singh Sikarwar Bhaiya RMC: So team we are gonna have a meeting on Saturday night, an online meet and for your notice no one can skip this meeting
8/8/24, 2:41 PM - Sayal Singh Sikarwar Bhaiya RMC: I saw anyone skipping the meeting they are gonna get a warning and you are gonna get only 1 warning then for the next warning you are out
8/8/24, 2:41 PM - Sayal Singh Sikarwar Bhaiya RMC: So yeah meeting on Saturday by 10
8/8/24, 2:41 PM - Sayal Singh Sikarwar Bhaiya RMC: Link will be shared
8/8/24, 2:42 PM - Sayal Singh Sikarwar Bhaiya RMC: I want reaction on this message
8/8/24, 3:47 PM - Sayal Singh Sikarwar Bhaiya RMC: Those who wanna work in creative text me asap
8/8/24, 10:03 PM - Akshada Didi RMC Vice - Secretary: https://docs.google.com/document/d/12zhOd9oPDi3YZhMFSTel4yeYG5Lhn8Bk-JEhVsHRlYA/edit?usp=sharing

event description

ignore round 3, use first two events
8/8/24, 10:04 PM - Akshada Didi RMC Vice - Secretary: crossword k liye similar to round 1 - bas crossword ka paper denge
8/8/24, 10:07 PM - Akshada Didi RMC Vice - Secretary: https://www.youtube.com/watch?v=nr8biZfSZ3Y&t=594s

check out the math part
8/10/24, 7:38 PM - Sayal Singh Sikarwar Bhaiya RMC: . Reminder 🎗️
8/10/24, 7:38 PM - Sayal Singh Sikarwar Bhaiya RMC: Mostly it's a 10 min work
8/10/24, 7:38 PM - Sayal Singh Sikarwar Bhaiya RMC: So kindly join
8/10/24, 9:53 PM - Sayal Singh Sikarwar Bhaiya RMC: To join the meeting on Google Meet, click this link:
https://meet.google.com/wnh-kbwg-mpi

Or open Meet and enter this code: wnh-kbwg-mpi
8/10/24, 9:53 PM - Sayal Singh Sikarwar Bhaiya RMC: Join fast
8/12/24, 10:35 AM - Sayal Singh Sikarwar Bhaiya RMC: We will meet tomorrow at 1PM in conference hall, mathematics department, 10th floor UB
8/12/24, 10:35 AM - Sayal Singh Sikarwar Bhaiya RMC: Everyone needs to attend the meeting
8/12/24, 11:36 AM - Kavya Singh: tomorrow as in Tuesday,right?
8/12/24, 11:37 AM - Sayal Singh Sikarwar Bhaiya RMC: Yeah
8/12/24, 11:38 AM - Kavya Singh: ok
8/12/24, 12:29 PM - +91 77189 12985: Bhaiya i have class at that time
8/12/24, 12:29 PM - Sayal Singh Sikarwar Bhaiya RMC: Bhai leave karna padega. Maine meeting mein kaha tha
8/12/24, 12:29 PM - +91 77189 12985: Fine koi na, i will come
8/13/24, 12:52 PM - Sayal Singh Sikarwar Bhaiya RMC: I am here , everyone please come
8/13/24, 1:04 PM - Rohit Girish SRM Roommate: On our way
8/13/24, 1:06 PM - Kavya Singh: whats the room no?
8/25/24, 12:01 AM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
8/25/24, 12:01 AM - Sayal Singh Sikarwar Bhaiya RMC: 🎉 *Join Ramanujan Mathematics Club!* 🎉

Do you have the zeal for mathematics and stoked curiosity to explore its beauty? 💫
RMC is inviting SRMites to be a part of our illustrious journey!🚀
From domains such as :

*Creatives 🎨*
*Technical 💻*
*Content ✏️*
*Events 🎤*
*Sponsorship 💰*
*Outreach 🔊*

There's something for everybody!
Apply now and let's make mathematics fun and engaging together! 📚 ✨

🔗 Scan the QR code to apply and follow us on Instagram @rmcatsrm.
8/25/24, 12:01 AM - Sayal Singh Sikarwar Bhaiya RMC: Share it with your class , Instagram WhatsApp
8/25/24, 6:44 PM - Sayal Singh Sikarwar Bhaiya RMC: @120363283633300637@g.us  every lead start preparing your domain interview questions and send them in their domain groups by tomorrow night
9/1/24, 11:06 PM - Anand RMC: This message was deleted
9/1/24, 11:13 PM - Abhradeep Paari 402: Bro isma mera name nahi hai
9/1/24, 11:13 PM - Anand RMC: Sorry, I'll edit it rn
9/1/24, 11:16 PM - Anand RMC: <Media omitted>
9/4/24, 9:31 PM - Anjul Kaari Room No. 506: !! Guys join fast !!
9/4/24, 9:32 PM - +91 91337 51494: Link?
9/4/24, 9:32 PM - Anjul Kaari Room No. 506: meet.google.com/jhk-uxmg-ihq

9.30 tak join kar lo
9/4/24, 9:32 PM - +91 77189 12985: https://meet.google.com/jhk-uxmg-ihq
9/4/24, 9:35 PM - Akshada Didi RMC Vice - Secretary: @918617424747 @918448833059 @918885450457 @918700645229 please join soon <This message was edited>
9/4/24, 9:36 PM - Satvik Sawhney Bhaiya RMC: Okk
9/4/24, 9:41 PM - Abhradeep Paari 402: yes joining
9/4/24, 10:46 PM - Chandrakant Subudhi: <Media omitted>
9/5/24, 7:22 AM - Chandrakant Subudhi: https://www.instagram.com/reel/C-fnZiBy-5e/?igsh=dXU0Z2t6dm14OHBt
9/5/24, 7:41 AM - Abhradeep Paari 402: https://www.instagram.com/reel/C-pm_mYIUce/?igsh=dXl4ZXduZ3d1NGgy
9/5/24, 7:44 AM - Chandrakant Subudhi: https://www.instagram.com/reel/C-nEGjUKPzl/?igsh=MWxhOHp2Y28wemUxZw==
9/5/24, 7:48 AM - Chandrakant Subudhi: https://www.instagram.com/reel/C8rVvKbyRqy/?igsh=d29yY2RjMnEzZGl4
9/5/24, 7:54 AM - Abhradeep Paari 402: https://www.instagram.com/reel/C_TM5D8MaiT/?igsh=cjFxcWlkemp3NXNh
9/5/24, 7:59 AM - +91 90070 58128: https://www.instagram.com/reel/C3pq5UsvDZK/?igsh=Mzd3NWUyZ25sbjJz
9/5/24, 7:59 AM - +91 90070 58128: https://www.instagram.com/reel/C4AGUjbvlZh/?igsh=M2NqenFuaDhreTNx
9/5/24, 12:04 PM - Chandrakant Subudhi: https://www.instagram.com/reel/C_TM5D8MaiT/?igsh=MWEzcG0xbTUzamlzZQ==
9/5/24, 12:04 PM - Chandrakant Subudhi: We can make this 1 day before the event
9/5/24, 12:17 PM - Anjul Kaari Room No. 506: <Media omitted>
9/5/24, 12:18 PM - Akshada Didi RMC Vice - Secretary: story kar de
9/5/24, 12:18 PM - Anjul Kaari Room No. 506: Done
9/5/24, 1:50 PM - Rohit Girish SRM Roommate: https://www.instagram.com/reel/C-LA79LqOD3/?igsh=NndoNzV5b3I1ajY5
9/5/24, 1:51 PM - Rohit Girish SRM Roommate: I was thinking about showcasing the event poster when they make sounds
- For the Instagram reel
9/13/24, 12:52 PM - Anjul Kaari Room No. 506: Who is free right now??
9/13/24, 12:59 PM - Sayal Singh Sikarwar Bhaiya RMC: Reply guys
9/13/24, 1:02 PM - Anand RMC: have class till 4
9/13/24, 1:03 PM - Anjul Kaari Room No. 506: I want 2,3 members for staff room publicity for recruitment plz respond we need to finish it today
9/13/24, 1:05 PM - +91 77189 12985: I have classes til 5
9/13/24, 1:18 PM - Rohit Girish SRM Roommate: I will be joining
9/13/24, 1:21 PM - Yashvardhan Singh: Me as well
9/13/24, 1:22 PM - +91 78773 95130: Till 5
9/13/24, 1:24 PM - Anjul Kaari Room No. 506: Those who cannot come give reason
9/13/24, 2:16 PM - Mudit Khater Senior: I am travelling back home so can't help
9/13/24, 9:57 PM - Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/nmn-myri-xgz
9/13/24, 10:01 PM - Sayal Singh Sikarwar Bhaiya RMC: @120363283633300637@g.us join everyone
9/13/24, 10:22 PM - +91 91337 51494: 1.	Sayal Singh
2.	Abhradeep Maity
3.	Anjul Shukla
4.	Akshada Kashyap
5.	Anand Arora
6.	Aqeel Umar
7.	Chandrakant S
8.	Deepshikha
9.	Harsh M
10.	Kabir Mishra
11.	Kavya Singh
12.	Rohit Girish
13.	Rohan
14.	Sahil
15.	Sukanya Konar
16.	Yashvardhan Singh
9/13/24, 10:40 PM - +91 91337 51494: <Media omitted>
9/13/24, 10:43 PM - Anjul Kaari Room No. 506: @918885450457  @919908208568 Give me all the data of publications you have contacted to for  sponsorship
9/16/24, 7:25 AM - Sayal Singh Sikarwar Bhaiya RMC: Guys do i need to remind about the deadlines that was given ??  Except events domain I have not got a single reply. Not about the reels also <This message was edited>
9/16/24, 7:49 AM - Kavya Singh: sorry for the delay...will be done by EOD
9/16/24, 4:52 PM - Sayal Singh Sikarwar Bhaiya RMC: Guys 57 responses. 20-25 gonna get selected. 50% first years
9/16/24, 4:53 PM - Sayal Singh Sikarwar Bhaiya RMC: So i need one lead from each domain today for a meet
9/16/24, 4:53 PM - Sayal Singh Sikarwar Bhaiya RMC: Meet @8
9/16/24, 7:10 PM - Sayal Singh Sikarwar Bhaiya RMC: Meet @9
9/16/24, 7:11 PM - Satvik Sawhney Bhaiya RMC: 8:15?
9/16/24, 7:14 PM - Sayal Singh Sikarwar Bhaiya RMC: Shifted
9/16/24, 9:00 PM - Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/aha-wbzv-njx
9/16/24, 9:06 PM - Sayal Singh Sikarwar Bhaiya RMC: Guys join fast
9/16/24, 9:24 PM - Sayal Singh Sikarwar Bhaiya RMC: https://docs.google.com/spreadsheets/d/1EMd8w_s-SHB7WbGtpPAGR4SoFi6NOfnI2fbE5CSJKT4/edit?usp=sharing
9/19/24, 2:40 AM - Sayal Singh Sikarwar Bhaiya RMC: Email has been sent out regarding interviews. Interview on Saturday and Sunday. Saturday technical & creative & outreach and sponsors
9/19/24, 2:40 AM - Sayal Singh Sikarwar Bhaiya RMC: Sunday content & eventa
9/19/24, 3:36 AM - Sayal Singh Sikarwar Bhaiya RMC: This message was deleted
9/19/24, 8:51 AM - Sayal Singh Sikarwar Bhaiya RMC: Meeting tomorrow night regarding Recruitment
9/19/24, 8:51 AM - Sayal Singh Sikarwar Bhaiya RMC: Everyone needs to be present
9/20/24, 9:05 PM - Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/moh-dcqo-mvm
9/21/24, 2:41 PM - Sayal Singh Sikarwar Bhaiya RMC: @918700645229  & @918885450457 @919908208568 @917095040612  start a Google meet by 2:50
9/21/24, 2:41 PM - Sayal Singh Sikarwar Bhaiya RMC: Send the links in this group
9/21/24, 2:47 PM - Satvik Sawhney Bhaiya RMC: https://meet.google.com/ikx-vkbm-bzd

Tech
9/21/24, 2:47 PM - Satvik Sawhney Bhaiya RMC: @919407397300
9/21/24, 2:49 PM - Rohit Girish SRM Roommate: https://meet.google.com/xjt-ycug-aau

Outreach and Sponsorship <This message was edited>
9/21/24, 2:50 PM - Sayal Singh Sikarwar Bhaiya RMC: Outreach and sponsor go hand in hand. First sponsor then outreach
9/21/24, 2:50 PM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
9/21/24, 2:50 PM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
9/21/24, 2:50 PM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
9/21/24, 2:50 PM - Sayal Singh Sikarwar Bhaiya RMC: Tech & creative
9/21/24, 2:50 PM - Sayal Singh Sikarwar Bhaiya RMC: Sponsors
9/21/24, 2:50 PM - Sayal Singh Sikarwar Bhaiya RMC: Outreach
9/21/24, 2:51 PM - Sayal Singh Sikarwar Bhaiya RMC: @918056032332 kindly join this
9/21/24, 2:51 PM - Sayal Singh Sikarwar Bhaiya RMC: @918056032332 share both the links in recruitment group by 2:55
9/21/24, 4:12 PM - Sayal Singh Sikarwar Bhaiya RMC: What are the updates
9/21/24, 4:13 PM - Rohit Girish SRM Roommate: So we have shortlisted two members
Omkar Sharma - Sponsorship
Keshav Gupta - Outreach <This message was edited>
9/21/24, 4:13 PM - Anjul Kaari Room No. 506: one outreach✅
9/21/24, 4:13 PM - Sayal Singh Sikarwar Bhaiya RMC: Ok cool guys
9/21/24, 4:13 PM - Anjul Kaari Room No. 506: one Sponsorship ✅
9/21/24, 4:14 PM - Anjul Kaari Room No. 506: baki three mail dubara send karenge
9/21/24, 4:15 PM - Anjul Kaari Room No. 506: yai bolne kai liye apka interview reschedule hua hai
9/22/24, 10:39 AM - Sayal Singh Sikarwar Bhaiya RMC: Today 3 interviews will be done at same time.
9/22/24, 10:39 AM - Sayal Singh Sikarwar Bhaiya RMC: Sayal Singh - Satvik - Aqeel - Technical & Creative
9/22/24, 10:40 AM - Sayal Singh Sikarwar Bhaiya RMC: Akshada - Yash - Harsh - Events
9/22/24, 10:40 AM - Sayal Singh Sikarwar Bhaiya RMC: Anjul - Kavya - Shakshi - Content
9/22/24, 10:40 AM - Sayal Singh Sikarwar Bhaiya RMC: Kindly acknowledge
9/22/24, 10:41 AM - Satvik Sawhney Bhaiya RMC: Ok 👍
9/22/24, 10:49 AM - Sayal Singh Sikarwar Bhaiya RMC: Sukanya can you please join this team for the interview
9/22/24, 2:19 PM - Sayal Singh Sikarwar Bhaiya RMC: @918056032332 @916261442894 @918700645229  make google links for gmeet
9/22/24, 2:23 PM - Satvik Sawhney Bhaiya RMC: https://meet.google.com/pgf-nsoh-irt

Technical and Creatives
9/22/24, 2:24 PM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
9/22/24, 2:24 PM - Sayal Singh Sikarwar Bhaiya RMC: Events Slots. Kindly react those names are in here .
9/22/24, 2:24 PM - Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>
9/22/24, 2:24 PM - Sayal Singh Sikarwar Bhaiya RMC: Content Slots. Kindly react those names are in here
9/22/24, 2:28 PM - Kavya Singh: baaki links?
9/22/24, 2:28 PM - Kavya Singh: for content and event
9/22/24, 2:28 PM - Sayal Singh Sikarwar Bhaiya RMC: Akshada is making up for events
9/22/24, 2:28 PM - Sayal Singh Sikarwar Bhaiya RMC: Anjul will make one for content
9/22/24, 2:33 PM - Akshada Didi RMC Vice - Secretary: https://meet.google.com/gff-syxb-cit

Events Link
9/22/24, 2:34 PM - Kavya Singh: https://meet.google.com/gvm-ziyx-ife

Content
9/22/24, 2:34 PM - Kavya Singh: anjul thoda busy hai isliye maine link bana di
9/22/24, 2:34 PM - Sayal Singh Sikarwar Bhaiya RMC: Okay
9/22/24, 2:35 PM - Akshada Didi RMC Vice - Secretary: @916307185068 tum bhi join kar lo events
9/22/24, 2:43 PM - Sayal Singh Sikarwar Bhaiya RMC: Guys kindly tag the link they should join, tu avoid the confusion
9/22/24, 2:47 PM - Sayal Singh Sikarwar Bhaiya RMC: Harsh Vardhan ka interview bhi le lena text kar raha @919423520162. After this interview
9/22/24, 2:47 PM - Anjul Kaari Room No. 506: Ok
9/22/24, 2:59 PM - Sayal Singh Sikarwar Bhaiya RMC: Iska kya hua ?
9/22/24, 2:59 PM - Kavya Singh: bas abhi wale k baad issi ko bola hai
9/22/24, 2:59 PM - Sayal Singh Sikarwar Bhaiya RMC: okk
9/23/24, 2:07 PM - Sayal Singh Sikarwar Bhaiya RMC: Meeting today @9. I know 2nd year has CTS. But it will be a metting only for 25-30 min. Kindly join and acknowledge.
9/23/24, 9:02 PM - Anjul Kaari Room No. 506: Link ?
9/23/24, 9:06 PM - +91 78773 95130: +1
9/23/24, 9:27 PM - Akshada Didi RMC Vice - Secretary: @919407397300 kya hua
9/23/24, 9:28 PM - Sayal Singh Sikarwar Bhaiya RMC: Sorry guys 2 min
9/23/24, 9:29 PM - Akshada Didi RMC Vice - Secretary: https://meet.google.com/qcf-fnrp-zrh

join kar lo guys
9/23/24, 9:29 PM - Akshada Didi RMC Vice - Secretary: 9.35 tak
9/24/24, 1:42 PM - Sayal Singh Sikarwar Bhaiya RMC: Guys meeting with Parvati Mam and other faculties. Kindly join by 6:50.
9/24/24, 1:42 PM - Sayal Singh Sikarwar Bhaiya RMC: No one should miss
9/24/24, 1:43 PM - Abhradeep Paari 402: Where
9/24/24, 1:44 PM - Sayal Singh Sikarwar Bhaiya RMC: Link bhejunga
9/24/24, 1:44 PM - Sayal Singh Sikarwar Bhaiya RMC: Kindly acknowledge
9/24/24, 6:46 PM - Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/kdm-swmi-xqf
9/24/24, 6:48 PM - Sayal Singh Sikarwar Bhaiya RMC: Join asap sir is waiting for us
9/24/24, 6:48 PM - Sayal Singh Sikarwar Bhaiya RMC: And come by official id
9/24/24, 7:14 PM - Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/rpi-ygao-dyr
9/24/24, 7:14 PM - Sayal Singh Sikarwar Bhaiya RMC: Yao sab
9/26/24, 11:21 PM - Rohit Girish SRM Roommate: All the interviews are done from our side
9/26/24, 11:21 PM - Rohit Girish SRM Roommate: The details of shortlisted candidates will be updated by tonight
9/28/24, 1:19 AM - Sayal Singh Sikarwar Bhaiya RMC: Meeting Schedule For Tomorrow :

Outreach regarding publicity  - *3 pm*

Content Regarding Question Paper  - *3.20 pm*

Events Regarding Event Flow - *3.40 pm*

Creative Regarding Certificate  - *4 pm*

Core team regarding Event Discussion and new recruits. - *4.20 pm*
9/28/24, 1:19 AM - Sayal Singh Sikarwar Bhaiya RMC: Kindly acknowledge
9/28/24, 1:19 AM - Sayal Singh Sikarwar Bhaiya RMC: 28 September 2024
9/28/24, 1:49 AM - Rohit Girish SRM Roommate: Online or Offline ? <This message was edited>
9/28/24, 1:50 AM - Sayal Singh Sikarwar Bhaiya RMC: Online
9/28/24, 3:04 PM - Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/qqb-zqfx-svd
9/28/24, 3:04 PM - Sayal Singh Sikarwar Bhaiya RMC: Join guys
9/28/24, 3:07 PM - Sayal Singh Sikarwar Bhaiya RMC: @919908208568 @917095040612 @918056032332 @916261442894  join in guys
9/28/24, 3:08 PM - Rohan Kaari Room No. 506: just a sec
9/28/24, 3:37 PM - Kavya Singh: @917296857259 please join

In [10]:
pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?(?:AM|PM)?\s-\s'

In [11]:
messages=re.split(pattern,data)[1:]
messages

['Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n',
 'Sayal Singh Sikarwar Bhaiya RMC created group "RMC\' 24 Official Members "\n',
 "You joined a group via invite in the community: RMC'24 Official\n",
 "+91 78773 95130 joined using this group's invite link\n",
 "Rohan Kaari Room No. 506 joined using this group's invite link\n",
 'Sayal Singh Sikarwar Bhaiya RMC added Abhradeep Paari 402\n',
 'Anjul Kaari Room No. 506: 🛑🛑🛑:-NOTICE-:🛑🛑🛑\n\nSubject: Mandatory Club Meeting – Next Saturday at 10 PM\n\nHello everyone,\n\nI hope this message finds you well.\n\nThis is to inform you that we will be holding a mandatory club meeting next Saturday at 10 PM. Your presence is compulsory, as we will be discussing important matters related to the upcoming tenure of the club.\n\nMeeting Details:\n**Date:** 29 JUNE\n**Time:** 10 PM\n**Venue:** Online\n\nThe agenda will include key topics and decisions that will shape our activities and plans for the next tenure. Your input and participation are crucial to ensure we have a successful and productive period ahead.\n\nPlease mark your calendars and make the necessary arrangements to attend this important meeting. If you have any questions or need further information, do not hesitate to reach out.\n\nLooking forward to seeing you all there.\n\nKindly acknowledge this message.\n\nRegards,\n',
 'Anjul Kaari Room No. 506 pinned a message\n',
 'Sayal Singh Sikarwar Bhaiya RMC: *REMINDER* 🟥🟥🟥\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Kindly Pay Attention \nThe meeting that was going to happen today has been shifted to tomorrow ( Sunday 30 June 2024) ,timing will be  9 p.m. \n\nThank you\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Kindly react @120363283633300637@g.us\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Reminder 🟥🟥\n',
 'Anjul Kaari Room No. 506: https://meet.google.com/obc-kdda-acq\n',
 'Anjul Kaari Room No. 506: Guys Join this meet on sharp 9:00\n',
 'Sayal Singh Sikarwar Bhaiya RMC added Satvik Sawhney Bhaiya RMC\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 "Sayal Singh Sikarwar Bhaiya RMC: All the board members today we are going to have an online meet by 9 pm. It's not a request. Everyone has to join , we are right now in a tough situation.\n",
 'Sayal Singh Sikarwar Bhaiya RMC: @120363283633300637@g.us\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Everyone has to react to this message\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Time can change 1 hr prior or 1 hr late so be prepared\n',
 "Sayal Singh Sikarwar Bhaiya RMC: And it's a serious thing\n",
 "Sayal Singh Sikarwar Bhaiya RMC: If there is ANYTHING why u can't join the meet tell now and please don't consider this as an excuse\n",
 'Sayal Singh Sikarwar Bhaiya RMC: Especially call-out to @918885450457  u have missed the last meet also without any specific reason\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 '+91 90070 58128: 🛑🛑🛑:-NOTICE-:🛑🛑🛑\n\nSubject: Mandatory Offline Meeting – 30/07/2024 at 5 PM\n\nHi everyone,\n\nThis is to inform you that an offline club meeting will be held on 30th July at 5 PM. Your presence is mandatory, as we will be discussing important matters related to the upcoming tenure of the club.\n\nMeeting Details:\n**Date:** 30 JULY\n**Time:** 5 PM\n**Venue:** In front of Architecture building \n\nReact to this message once you receive it.\n\nThank you!\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Reminder 🟥🟥🟥\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Everyone come fast\n',
 "Akshada Didi RMC Vice - Secretary changed this group's settings to allow all members to send messages to this group\n",
 "Akshada Didi RMC Vice - Secretary changed this group's settings to allow only admins to send messages to this group\n",
 "Akshada Didi RMC Vice - Secretary changed this group's settings to allow all members to send messages to this group\n",
 "Akshada Didi RMC Vice - Secretary: good evening, everyone 🙏🏼\n\nalongside starting our prep for IMF'24, we should start focusing on growing our Instagram acc too, and so I'm hoping we start a discussion on the same here\n\npls post your ideas on how to do the same: reel ideas, engaging posts/stories, etc. \n\nhoping for everyone to respond 👾\n",
 'Akshada Didi RMC Vice - Secretary: I was thinking we gather ideas on integrating mathematics w memes, and make reels that way\n\npost 2-3 per week\n',
 'Sayal Singh Sikarwar Bhaiya RMC: So team we are gonna have a meeting on Saturday night, an online meet and for your notice no one can skip this meeting\n',
 'Sayal Singh Sikarwar Bhaiya RMC: I saw anyone skipping the meeting they are gonna get a warning and you are gonna get only 1 warning then for the next warning you are out\n',
 'Sayal Singh Sikarwar Bhaiya RMC: So yeah meeting on Saturday by 10\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Link will be shared\n',
 'Sayal Singh Sikarwar Bhaiya RMC: I want reaction on this message\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Those who wanna work in creative text me asap\n',
 'Akshada Didi RMC Vice - Secretary: https://docs.google.com/document/d/12zhOd9oPDi3YZhMFSTel4yeYG5Lhn8Bk-JEhVsHRlYA/edit?usp=sharing\n\nevent description\n\nignore round 3, use first two events\n',
 'Akshada Didi RMC Vice - Secretary: crossword k liye similar to round 1 - bas crossword ka paper denge\n',
 'Akshada Didi RMC Vice - Secretary: https://www.youtube.com/watch?v=nr8biZfSZ3Y&t=594s\n\ncheck out the math part\n',
 'Sayal Singh Sikarwar Bhaiya RMC: . Reminder 🎗️\n',
 "Sayal Singh Sikarwar Bhaiya RMC: Mostly it's a 10 min work\n",
 'Sayal Singh Sikarwar Bhaiya RMC: So kindly join\n',
 'Sayal Singh Sikarwar Bhaiya RMC: To join the meeting on Google Meet, click this link: \nhttps://meet.google.com/wnh-kbwg-mpi \n \nOr open Meet and enter this code: wnh-kbwg-mpi\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Join fast\n',
 'Sayal Singh Sikarwar Bhaiya RMC: We will meet tomorrow at 1PM in conference hall, mathematics department, 10th floor UB\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Everyone needs to attend the meeting\n',
 'Kavya Singh: tomorrow as in Tuesday,right?\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Yeah\n',
 'Kavya Singh: ok\n',
 '+91 77189 12985: Bhaiya i have class at that time\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Bhai leave karna padega. Maine meeting mein kaha tha\n',
 '+91 77189 12985: Fine koi na, i will come\n',
 'Sayal Singh Sikarwar Bhaiya RMC: I am here , everyone please come\n',
 'Rohit Girish SRM Roommate: On our way\n',
 'Kavya Singh: whats the room no?\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 "Sayal Singh Sikarwar Bhaiya RMC: 🎉 *Join Ramanujan Mathematics Club!* 🎉\n\nDo you have the zeal for mathematics and stoked curiosity to explore its beauty? 💫 \nRMC is inviting SRMites to be a part of our illustrious journey!🚀\nFrom domains such as :\n\n*Creatives 🎨*\n*Technical 💻*\n*Content ✏️*\n*Events 🎤*\n*Sponsorship 💰*\n*Outreach 🔊*\n\nThere's something for everybody! \nApply now and let's make mathematics fun and engaging together! 📚 ✨\n\n🔗 Scan the QR code to apply and follow us on Instagram @rmcatsrm.\n",
 'Sayal Singh Sikarwar Bhaiya RMC: Share it with your class , Instagram WhatsApp\n',
 'Sayal Singh Sikarwar Bhaiya RMC: @120363283633300637@g.us  every lead start preparing your domain interview questions and send them in their domain groups by tomorrow night\n',
 'Anand RMC: This message was deleted\n',
 'Abhradeep Paari 402: Bro isma mera name nahi hai\n',
 "Anand RMC: Sorry, I'll edit it rn\n",
 'Anand RMC: <Media omitted>\n',
 'Anjul Kaari Room No. 506: !! Guys join fast !!\n',
 '+91 91337 51494: Link?\n',
 'Anjul Kaari Room No. 506: meet.google.com/jhk-uxmg-ihq\n\n9.30 tak join kar lo\n',
 '+91 77189 12985: https://meet.google.com/jhk-uxmg-ihq\n',
 'Akshada Didi RMC Vice - Secretary: @918617424747 @918448833059 @918885450457 @918700645229 please join soon <This message was edited>\n',
 'Satvik Sawhney Bhaiya RMC: Okk\n',
 'Abhradeep Paari 402: yes joining\n',
 'Chandrakant Subudhi: <Media omitted>\n',
 'Chandrakant Subudhi: https://www.instagram.com/reel/C-fnZiBy-5e/?igsh=dXU0Z2t6dm14OHBt\n',
 'Abhradeep Paari 402: https://www.instagram.com/reel/C-pm_mYIUce/?igsh=dXl4ZXduZ3d1NGgy\n',
 'Chandrakant Subudhi: https://www.instagram.com/reel/C-nEGjUKPzl/?igsh=MWxhOHp2Y28wemUxZw==\n',
 'Chandrakant Subudhi: https://www.instagram.com/reel/C8rVvKbyRqy/?igsh=d29yY2RjMnEzZGl4\n',
 'Abhradeep Paari 402: https://www.instagram.com/reel/C_TM5D8MaiT/?igsh=cjFxcWlkemp3NXNh\n',
 '+91 90070 58128: https://www.instagram.com/reel/C3pq5UsvDZK/?igsh=Mzd3NWUyZ25sbjJz\n',
 '+91 90070 58128: https://www.instagram.com/reel/C4AGUjbvlZh/?igsh=M2NqenFuaDhreTNx\n',
 'Chandrakant Subudhi: https://www.instagram.com/reel/C_TM5D8MaiT/?igsh=MWEzcG0xbTUzamlzZQ==\n',
 'Chandrakant Subudhi: We can make this 1 day before the event\n',
 'Anjul Kaari Room No. 506: <Media omitted>\n',
 'Akshada Didi RMC Vice - Secretary: story kar de\n',
 'Anjul Kaari Room No. 506: Done\n',
 'Rohit Girish SRM Roommate: https://www.instagram.com/reel/C-LA79LqOD3/?igsh=NndoNzV5b3I1ajY5\n',
 'Rohit Girish SRM Roommate: I was thinking about showcasing the event poster when they make sounds \n- For the Instagram reel\n',
 'Anjul Kaari Room No. 506: Who is free right now??\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Reply guys\n',
 'Anand RMC: have class till 4\n',
 'Anjul Kaari Room No. 506: I want 2,3 members for staff room publicity for recruitment plz respond we need to finish it today\n',
 '+91 77189 12985: I have classes til 5\n',
 'Rohit Girish SRM Roommate: I will be joining\n',
 'Yashvardhan Singh: Me as well\n',
 '+91 78773 95130: Till 5\n',
 'Anjul Kaari Room No. 506: Those who cannot come give reason\n',
 "Mudit Khater Senior: I am travelling back home so can't help\n",
 'Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/nmn-myri-xgz\n',
 'Sayal Singh Sikarwar Bhaiya RMC: @120363283633300637@g.us join everyone\n',
 '+91 91337 51494: 1.\tSayal Singh\n2.\tAbhradeep Maity\n3.\tAnjul Shukla\n4.\tAkshada Kashyap \n5.\tAnand Arora\n6.\tAqeel Umar\n7.\tChandrakant S\n8.\tDeepshikha\n9.\tHarsh M\n10.\tKabir Mishra\n11.\tKavya Singh\n12.\tRohit Girish\n13.\tRohan\n14.\tSahil\n15.\tSukanya Konar\n16.\tYashvardhan Singh\n',
 '+91 91337 51494: <Media omitted>\n',
 'Anjul Kaari Room No. 506: @918885450457  @919908208568 Give me all the data of publications you have contacted to for  sponsorship\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Guys do i need to remind about the deadlines that was given ??  Except events domain I have not got a single reply. Not about the reels also <This message was edited>\n',
 'Kavya Singh: sorry for the delay...will be done by EOD\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Guys 57 responses. 20-25 gonna get selected. 50% first years\n',
 'Sayal Singh Sikarwar Bhaiya RMC: So i need one lead from each domain today for a meet\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Meet @8\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Meet @9\n',
 'Satvik Sawhney Bhaiya RMC: 8:15?\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Shifted\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/aha-wbzv-njx\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Guys join fast\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://docs.google.com/spreadsheets/d/1EMd8w_s-SHB7WbGtpPAGR4SoFi6NOfnI2fbE5CSJKT4/edit?usp=sharing\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Email has been sent out regarding interviews. Interview on Saturday and Sunday. Saturday technical & creative & outreach and sponsors\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Sunday content & eventa\n',
 'Sayal Singh Sikarwar Bhaiya RMC: This message was deleted\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Meeting tomorrow night regarding Recruitment\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Everyone needs to be present\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/moh-dcqo-mvm\n',
 'Sayal Singh Sikarwar Bhaiya RMC: @918700645229  & @918885450457 @919908208568 @917095040612  start a Google meet by 2:50\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Send the links in this group\n',
 'Satvik Sawhney Bhaiya RMC: https://meet.google.com/ikx-vkbm-bzd\n\nTech\n',
 'Satvik Sawhney Bhaiya RMC: @919407397300\n',
 'Rohit Girish SRM Roommate: https://meet.google.com/xjt-ycug-aau\n\nOutreach and Sponsorship <This message was edited>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Outreach and sponsor go hand in hand. First sponsor then outreach\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Tech & creative\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Sponsors\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Outreach\n',
 'Sayal Singh Sikarwar Bhaiya RMC: @918056032332 kindly join this\n',
 'Sayal Singh Sikarwar Bhaiya RMC: @918056032332 share both the links in recruitment group by 2:55\n',
 'Sayal Singh Sikarwar Bhaiya RMC: What are the updates\n',
 'Rohit Girish SRM Roommate: So we have shortlisted two members \nOmkar Sharma - Sponsorship \nKeshav Gupta - Outreach <This message was edited>\n',
 'Anjul Kaari Room No. 506: one outreach✅\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Ok cool guys\n',
 'Anjul Kaari Room No. 506: one Sponsorship ✅\n',
 'Anjul Kaari Room No. 506: baki three mail dubara send karenge\n',
 'Anjul Kaari Room No. 506: yai bolne kai liye apka interview reschedule hua hai\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Today 3 interviews will be done at same time.\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Sayal Singh - Satvik - Aqeel - Technical & Creative\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Akshada - Yash - Harsh - Events\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Anjul - Kavya - Shakshi - Content\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Kindly acknowledge\n',
 'Satvik Sawhney Bhaiya RMC: Ok 👍\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Sukanya can you please join this team for the interview\n',
 'Sayal Singh Sikarwar Bhaiya RMC: @918056032332 @916261442894 @918700645229  make google links for gmeet\n',
 'Satvik Sawhney Bhaiya RMC: https://meet.google.com/pgf-nsoh-irt\n\nTechnical and Creatives\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Events Slots. Kindly react those names are in here .\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Content Slots. Kindly react those names are in here\n',
 'Kavya Singh: baaki links?\n',
 'Kavya Singh: for content and event\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Akshada is making up for events\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Anjul will make one for content\n',
 'Akshada Didi RMC Vice - Secretary: https://meet.google.com/gff-syxb-cit\n\nEvents Link\n',
 'Kavya Singh: https://meet.google.com/gvm-ziyx-ife\n\nContent\n',
 'Kavya Singh: anjul thoda busy hai isliye maine link bana di\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Okay\n',
 'Akshada Didi RMC Vice - Secretary: @916307185068 tum bhi join kar lo events\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Guys kindly tag the link they should join, tu avoid the confusion\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Harsh Vardhan ka interview bhi le lena text kar raha @919423520162. After this interview\n',
 'Anjul Kaari Room No. 506: Ok\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Iska kya hua ?\n',
 'Kavya Singh: bas abhi wale k baad issi ko bola hai\n',
 'Sayal Singh Sikarwar Bhaiya RMC: okk\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Meeting today @9. I know 2nd year has CTS. But it will be a metting only for 25-30 min. Kindly join and acknowledge.\n',
 'Anjul Kaari Room No. 506: Link ?\n',
 '+91 78773 95130: +1\n',
 'Akshada Didi RMC Vice - Secretary: @919407397300 kya hua\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Sorry guys 2 min\n',
 'Akshada Didi RMC Vice - Secretary: https://meet.google.com/qcf-fnrp-zrh\n\njoin kar lo guys\n',
 'Akshada Didi RMC Vice - Secretary: 9.35 tak\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Guys meeting with Parvati Mam and other faculties. Kindly join by 6:50.\n',
 'Sayal Singh Sikarwar Bhaiya RMC: No one should miss\n',
 'Abhradeep Paari 402: Where\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Link bhejunga\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Kindly acknowledge\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/kdm-swmi-xqf\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Join asap sir is waiting for us\n',
 'Sayal Singh Sikarwar Bhaiya RMC: And come by official id\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/rpi-ygao-dyr\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Yao sab\n',
 'Rohit Girish SRM Roommate: All the interviews are done from our side\n',
 'Rohit Girish SRM Roommate: The details of shortlisted candidates will be updated by tonight\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Meeting Schedule For Tomorrow :\n\nOutreach regarding publicity  - *3 pm*\n\nContent Regarding Question Paper  - *3.20 pm*\n\nEvents Regarding Event Flow - *3.40 pm*\n\nCreative Regarding Certificate  - *4 pm*\n\nCore team regarding Event Discussion and new recruits. - *4.20 pm*\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Kindly acknowledge\n',
 'Sayal Singh Sikarwar Bhaiya RMC: 28 September 2024\n',
 'Rohit Girish SRM Roommate: Online or Offline ? <This message was edited>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Online\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/qqb-zqfx-svd\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Join guys\n',
 'Sayal Singh Sikarwar Bhaiya RMC: @919908208568 @917095040612 @918056032332 @916261442894  join in guys\n',
 'Rohan Kaari Room No. 506: just a sec\n',
 'Kavya Singh: @917296857259 please join\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Creative domain join the meeting\n',
 '+91 77189 12985: Joining in 2 mins\n',
 'Rohan Kaari Room No. 506: https://docs.google.com/forms/d/e/1FAIpQLSebbECELBprWGrd6gKc4V1vMrAS5jft2jjqMw8D29q3nN76LQ/viewform\n',
 'Rohan Kaari Room No. 506: Hey guys, Please fill out this form before 10PM today. \nNote: Everyone is expected to fill this form including the leads\n',
 'Kavya Singh: Hey everyone! We need emcees for our event on 4th Oct\n',
 'Kavya Singh: so whoever is interested add in your names here\n1.\n',
 '+91 84488 33059: so whoever is interested add in your names here\n1.Prasanjit Panda\n',
 '+91 90070 58128: so whoever is interested add in your names here\n1.Prasanjit Panda\n2.Sukanya Konar\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Guys kindly put up your name. @120363283633300637@g.us\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Tomorrow Orientation Meet for freshers. 8 pm to 10 pm. Kindly be available\n',
 'Sayal Singh Sikarwar Bhaiya RMC pinned a message\n',
 'Rohan Kaari Room No. 506: @918948179588 @919908208568 @918885450457 @919007058128 @916307185068 @917509526000 @917718912985 @917877395130 @918700645229 @919133751494 \nGuys you were supposed to fill this form by 10PM. Please be responsive and fill it *ASAP*!!!\n',
 'Rohit Girish SRM Roommate: Done Already\n',
 'Sayal Singh Sikarwar Bhaiya RMC: 8:30 to 10:30 new timings\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://www.instagram.com/p/DAfjIoIBs_Y/?igsh=aTIzZmw4dG01eTVh\n',
 "Sayal Singh Sikarwar Bhaiya RMC: Let's go SRM official page shared our event\n",
 'Kavya Singh: damnn✨✨✨\n',
 'Sayal Singh Sikarwar Bhaiya RMC: BC hata diya\n',
 'Sayal Singh Sikarwar Bhaiya RMC: <Media omitted>\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Ho jayega i guess 🤞🤞\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://www.instagram.com/p/DAgEji9JySl/?igsh=b3AweTFnbWVqNHU0\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Done guys 🎉🎉\n',
 'Sayal Singh Sikarwar Bhaiya RMC: https://meet.google.com/ksy-ifvy-xgr\n',
 'Kavya Singh: all of u join\n',
 'Sayal Singh Sikarwar Bhaiya RMC: Guys join asap\n',
 "+91 94866 55032 joined using this group's invite link\n",
 "+91 99946 53009 joined using this group's invite link\n",
 "Saurav D Praveen Junior RMC Events Domain joined using this group's invite link\n",
 "Mukti RMC joined using this group's invite link\n",
 "+91 96324 32782 joined using this group's invite link\n",

In [12]:
dates=re.findall(pattern,data)
dates

['5/26/24, 9:06\u202fAM - ',
 '5/25/24, 10:10\u202fPM - ',
 '5/26/24, 9:06\u202fAM - ',
 '5/26/24, 11:04\u202fAM - ',
 '5/26/24, 4:14\u202fPM - ',
 '5/26/24, 6:49\u202fPM - ',
 '6/22/24, 2:54\u202fPM - ',
 '6/24/24, 7:32\u202fPM - ',
 '6/29/24, 11:46\u202fAM - ',
 '6/29/24, 1:18\u202fPM - ',
 '6/29/24, 1:19\u202fPM - ',
 '6/30/24, 8:32\u202fPM - ',
 '6/30/24, 8:57\u202fPM - ',
 '6/30/24, 8:58\u202fPM - ',
 '6/30/24, 9:02\u202fPM - ',
 '6/30/24, 10:45\u202fPM - ',
 '7/8/24, 12:53\u202fPM - ',
 '7/8/24, 12:53\u202fPM - ',
 '7/8/24, 12:53\u202fPM - ',
 '7/8/24, 12:53\u202fPM - ',
 '7/8/24, 12:53\u202fPM - ',
 '7/8/24, 12:54\u202fPM - ',
 '7/8/24, 12:54\u202fPM - ',
 '7/8/24, 9:47\u202fPM - ',
 '7/28/24, 7:23\u202fAM - ',
 '7/30/24, 11:14\u202fAM - ',
 '7/30/24, 4:59\u202fPM - ',
 '8/2/24, 6:43\u202fPM - ',
 '8/2/24, 6:43\u202fPM - ',
 '8/2/24, 6:43\u202fPM - ',
 '8/2/24, 6:41\u202fPM - ',
 '8/2/24, 6:42\u202fPM - ',
 '8/8/24, 2:40\u202fPM - ',
 '8/8/24, 2:41\u202fPM - ',
 '8/8/24, 2:41\u202fPM - ',
 '8/8/24, 2:41\u202fPM - ',
 '8/8/24, 2:42\u202fPM - ',
 '8/8/24, 3:47\u202fPM - ',
 '8/8/24, 10:03\u202fPM - ',
 '8/8/24, 10:04\u202fPM - ',
 '8/8/24, 10:07\u202fPM - ',
 '8/10/24, 7:38\u202fPM - ',
 '8/10/24, 7:38\u202fPM - ',
 '8/10/24, 7:38\u202fPM - ',
 '8/10/24, 9:53\u202fPM - ',
 '8/10/24, 9:53\u202fPM - ',
 '8/12/24, 10:35\u202fAM - ',
 '8/12/24, 10:35\u202fAM - ',
 '8/12/24, 11:36\u202fAM - ',
 '8/12/24, 11:37\u202fAM - ',
 '8/12/24, 11:38\u202fAM - ',
 '8/12/24, 12:29\u202fPM - ',
 '8/12/24, 12:29\u202fPM - ',
 '8/12/24, 12:29\u202fPM - ',
 '8/13/24, 12:52\u202fPM - ',
 '8/13/24, 1:04\u202fPM - ',
 '8/13/24, 1:06\u202fPM - ',
 '8/25/24, 12:01\u202fAM - ',
 '8/25/24, 12:01\u202fAM - ',
 '8/25/24, 12:01\u202fAM - ',
 '8/25/24, 6:44\u202fPM - ',
 '9/1/24, 11:06\u202fPM - ',
 '9/1/24, 11:13\u202fPM - ',
 '9/1/24, 11:13\u202fPM - ',
 '9/1/24, 11:16\u202fPM - ',
 '9/4/24, 9:31\u202fPM - ',
 '9/4/24, 9:32\u202fPM - ',
 '9/4/24, 9:32\u202fPM - ',
 '9/4/24, 9:32\u202fPM - ',
 '9/4/24, 9:35\u202fPM - ',
 '9/4/24, 9:36\u202fPM - ',
 '9/4/24, 9:41\u202fPM - ',
 '9/4/24, 10:46\u202fPM - ',
 '9/5/24, 7:22\u202fAM - ',
 '9/5/24, 7:41\u202fAM - ',
 '9/5/24, 7:44\u202fAM - ',
 '9/5/24, 7:48\u202fAM - ',
 '9/5/24, 7:54\u202fAM - ',
 '9/5/24, 7:59\u202fAM - ',
 '9/5/24, 7:59\u202fAM - ',
 '9/5/24, 12:04\u202fPM - ',
 '9/5/24, 12:04\u202fPM - ',
 '9/5/24, 12:17\u202fPM - ',
 '9/5/24, 12:18\u202fPM - ',
 '9/5/24, 12:18\u202fPM - ',
 '9/5/24, 1:50\u202fPM - ',
 '9/5/24, 1:51\u202fPM - ',
 '9/13/24, 12:52\u202fPM - ',
 '9/13/24, 12:59\u202fPM - ',
 '9/13/24, 1:02\u202fPM - ',
 '9/13/24, 1:03\u202fPM - ',
 '9/13/24, 1:05\u202fPM - ',
 '9/13/24, 1:18\u202fPM - ',
 '9/13/24, 1:21\u202fPM - ',
 '9/13/24, 1:22\u202fPM - ',
 '9/13/24, 1:24\u202fPM - ',
 '9/13/24, 2:16\u202fPM - ',
 '9/13/24, 9:57\u202fPM - ',
 '9/13/24, 10:01\u202fPM - ',
 '9/13/24, 10:22\u202fPM - ',
 '9/13/24, 10:40\u202fPM - ',
 '9/13/24, 10:43\u202fPM - ',
 '9/16/24, 7:25\u202fAM - ',
 '9/16/24, 7:49\u202fAM - ',
 '9/16/24, 4:52\u202fPM - ',
 '9/16/24, 4:53\u202fPM - ',
 '9/16/24, 4:53\u202fPM - ',
 '9/16/24, 7:10\u202fPM - ',
 '9/16/24, 7:11\u202fPM - ',
 '9/16/24, 7:14\u202fPM - ',
 '9/16/24, 9:00\u202fPM - ',
 '9/16/24, 9:06\u202fPM - ',
 '9/16/24, 9:24\u202fPM - ',
 '9/19/24, 2:40\u202fAM - ',
 '9/19/24, 2:40\u202fAM - ',
 '9/19/24, 3:36\u202fAM - ',
 '9/19/24, 8:51\u202fAM - ',
 '9/19/24, 8:51\u202fAM - ',
 '9/20/24, 9:05\u202fPM - ',
 '9/21/24, 2:41\u202fPM - ',
 '9/21/24, 2:41\u202fPM - ',
 '9/21/24, 2:47\u202fPM - ',
 '9/21/24, 2:47\u202fPM - ',
 '9/21/24, 2:49\u202fPM - ',
 '9/21/24, 2:50\u202fPM - ',
 '9/21/24, 2:50\u202fPM - ',
 '9/21/24, 2:50\u202fPM - ',
 '9/21/24, 2:50\u202fPM - ',
 '9/21/24, 2:50\u202fPM - ',
 '9/21/24, 2:50\u202fPM - ',
 '9/21/24, 2:50\u202fPM - ',
 '9/21/24, 2:51\u202fPM - ',
 '9/21/24, 2:51\u202fPM - ',
 '9/21/24, 4:12\u202fPM - ',
 '9/21/24, 4:13\u202fPM - ',
 '9/21/24, 4:13\u202fPM - ',
 '9/21/24, 4:13\u202fPM - ',
 '9/21/24, 4:13\u202fPM - ',
 '9/21/24, 4:14\u202fPM - ',
 '9/21/24, 4:15\u202fPM - ',
 '9/22/24, 10:39\u202fAM - ',
 '9/22/24, 10:39\u202fAM - ',
 '9/22/24, 10:40\u202fAM - ',
 '9/22/24, 10:40\u202fAM - ',
 '9/22/24, 10:40\u202fAM - ',
 '9/22/24, 10:41\u202fAM - ',
 '9/22/24, 10:49\u202fAM - ',
 '9/22/24, 2:19\u202fPM - ',
 '9/22/24, 2:23\u202fPM - ',
 '9/22/24, 2:24\u202fPM - ',
 '9/22/24, 2:24\u202fPM - ',
 '9/22/24, 2:24\u202fPM - ',
 '9/22/24, 2:24\u202fPM - ',
 '9/22/24, 2:28\u202fPM - ',
 '9/22/24, 2:28\u202fPM - ',
 '9/22/24, 2:28\u202fPM - ',
 '9/22/24, 2:28\u202fPM - ',
 '9/22/24, 2:33\u202fPM - ',
 '9/22/24, 2:34\u202fPM - ',
 '9/22/24, 2:34\u202fPM - ',
 '9/22/24, 2:34\u202fPM - ',
 '9/22/24, 2:35\u202fPM - ',
 '9/22/24, 2:43\u202fPM - ',
 '9/22/24, 2:47\u202fPM - ',
 '9/22/24, 2:47\u202fPM - ',
 '9/22/24, 2:59\u202fPM - ',
 '9/22/24, 2:59\u202fPM - ',
 '9/22/24, 2:59\u202fPM - ',
 '9/23/24, 2:07\u202fPM - ',
 '9/23/24, 9:02\u202fPM - ',
 '9/23/24, 9:06\u202fPM - ',
 '9/23/24, 9:27\u202fPM - ',
 '9/23/24, 9:28\u202fPM - ',
 '9/23/24, 9:29\u202fPM - ',
 '9/23/24, 9:29\u202fPM - ',
 '9/24/24, 1:42\u202fPM - ',
 '9/24/24, 1:42\u202fPM - ',
 '9/24/24, 1:43\u202fPM - ',
 '9/24/24, 1:44\u202fPM - ',
 '9/24/24, 1:44\u202fPM - ',
 '9/24/24, 6:46\u202fPM - ',
 '9/24/24, 6:48\u202fPM - ',
 '9/24/24, 6:48\u202fPM - ',
 '9/24/24, 7:14\u202fPM - ',
 '9/24/24, 7:14\u202fPM - ',
 '9/26/24, 11:21\u202fPM - ',
 '9/26/24, 11:21\u202fPM - ',
 '9/28/24, 1:19\u202fAM - ',
 '9/28/24, 1:19\u202fAM - ',
 '9/28/24, 1:19\u202fAM - ',
 '9/28/24, 1:49\u202fAM - ',
 '9/28/24, 1:50\u202fAM - ',
 '9/28/24, 3:04\u202fPM - ',
 '9/28/24, 3:04\u202fPM - ',
 '9/28/24, 3:07\u202fPM - ',
 '9/28/24, 3:08\u202fPM - ',
 '9/28/24, 3:37\u202fPM - ',
 '9/28/24, 3:59\u202fPM - ',
 '9/28/24, 4:01\u202fPM - ',
 '9/28/24, 5:04\u202fPM - ',
 '9/28/24, 5:06\u202fPM - ',
 '9/28/24, 8:58\u202fPM - ',
 '9/28/24, 8:58\u202fPM - ',
 '9/28/24, 8:59\u202fPM - ',
 '9/28/24, 9:02\u202fPM - ',
 '9/28/24, 11:11\u202fPM - ',
 '9/28/24, 11:21\u202fPM - ',
 '9/28/24, 11:22\u202fPM - ',
 '9/28/24, 11:24\u202fPM - ',
 '9/28/24, 11:56\u202fPM - ',
 '9/29/24, 7:49\u202fAM - ',
 '9/29/24, 1:11\u202fPM - ',
 '9/29/24, 1:11\u202fPM - ',
 '9/29/24, 1:12\u202fPM - ',
 '9/29/24, 1:16\u202fPM - ',
 '9/29/24, 1:35\u202fPM - ',
 '9/29/24, 1:36\u202fPM - ',
 '9/29/24, 6:10\u202fPM - ',
 '9/29/24, 6:10\u202fPM - ',
 '9/29/24, 8:31\u202fPM - ',
 '9/29/24, 8:32\u202fPM - ',
 '9/29/24, 8:34\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:08\u202fPM - ',
 '9/29/24, 9:09\u202fPM - ',
 '9/29/24, 9:15\u202fPM - ',
 '9/29/24, 9:22\u202fPM - ',
 '9/29/24, 9:39\u202fPM - ',
 '9/29/24, 10:13\u202fPM - ',
 '9/29/24, 10:54\u202fPM - ',
 '9/30/24, 12:29\u202fAM - ',
 '9/30/24, 7:28\u202fAM - ',
 '9/30/24, 7:53\u202fAM - ',
 '9/30/24, 7:53\u202fAM - ',
 '9/30/24, 7:56\u202fAM - ',
 '9/30/24, 7:57\u202fAM - ',
 '9/30/24, 8:27\u202fAM - ',
 '9/30/24, 8:27\u202fAM - ',
 '9/30/24, 9:46\u202fAM - ',
 '9/30/24, 10:17\u202fAM - ',
 '9/30/24, 10:17\u202fAM - ',
 '9/30/24, 10:54\u202fAM - ',
 '9/30/24, 11:09\u202fAM - ',
 '9/30/24, 11:15\u202fAM - ',
 '9/30/24, 12:03\u202fPM - ',
 '9/30/24, 1:06\u202fPM - ',
 '9/30/24, 1:06\u202fPM - ',
 '9/30/24, 1:06\u202fPM - ',
 '9/30/24, 1:07\u202fPM - ',
 '9/30/24, 1:09\u202fPM - ',
 '9/30/24, 1:09\u202fPM - ',
 '9/30/24, 1:09\u202fPM - ',
 '9/30/24, 1:12\u202fPM - ',
 '9/30/24, 6:13\u202fPM - ',
 '9/30/24, 6:13\u202fPM - ',
 '9/30/24, 6:14\u202fPM - ',
 '9/30/24, 6:14\u202fPM - ',
 '9/30/24, 6:28\u202fPM - ',
 '9/30/24, 6:28\u202fPM - ',
 '9/30/24, 6:28\u202fPM - ',
 '9/30/24, 7:15\u202fPM - ',
 '9/30/24, 7:17\u202fPM - ',
 '9/30/24, 7:30\u202fPM - ',
 '9/30/24, 7:30\u202fPM - ',
 '9/30/24, 7:31\u202fPM - ',
 '9/30/24, 7:36\u202fPM - ',
 '9/30/24, 7:36\u202fPM - ',
 '9/30/24, 7:37\u202fPM - ',
 '9/30/24, 8:03\u202fPM - ',
 '9/30/24, 8:04\u202fPM - ',
 '9/30/24, 8:05\u202fPM - ',
 '9/30/24, 8:05\u202fPM - ',
 '9/30/24, 8:05\u202fPM - ',
 '9/30/24, 8:05\u202fPM - ',
 '9/30/24, 8:08\u202fPM - ',
 '9/30/24, 8:08\u202fPM - ',
 '9/30/24, 8:37\u202fPM - ',
 '9/30/24, 8:37\u202fPM - ',
 '9/30/24, 8:38\u202fPM - ',
 '9/30/24, 8:56\u202fPM - ',
 '9/30/24, 8:57\u202fPM - ',
 '9/30/24, 8:57\u202fPM - ',
 '9/30/24, 8:57\u202fPM - ',
 '9/30/24, 8:59\u202fPM - ',
 '9/30/24, 8:59\u202fPM - ',
 '9/30/24, 9:01\u202fPM - ',
 '10/1/24, 12:23\u202fAM - ',
 '10/1/24, 12:51\u202fAM - ',
 '10/1/24, 6:18\u202fAM - ',
 '10/1/24, 6:36\u202fAM - ',
 '10/1/24, 6:37\u202fAM - ',
 '10/1/24, 7:44\u202fAM - ',
 '10/1/24, 12:01\u202fPM - ',
 '10/1/24, 12:01\u202fPM - ',
 '10/1/24, 12:02\u202fPM - ',
 '10/1/24, 12:03\u202fPM - ',
 '10/1/24, 12:04\u202fPM - ',
 '10/1/24, 12:04\u202fPM - ',
 '10/1/24, 12:04\u202fPM - ',
 '10/1/24, 12:04\u202fPM - ',
 '10/1/24, 12:05\u202fPM - ',
 '10/1/24, 12:05\u202fPM - ',
 '10/1/24, 12:05\u202fPM - ',
 '10/1/24, 12:06\u202fPM - ',
 '10/1/24, 12:06\u202fPM - ',
 '10/1/24, 12:06\u202fPM - ',
 '10/1/24, 12:07\u202fPM - ',
 '10/1/24, 12:08\u202fPM - ',
 '10/1/24, 12:15\u202fPM - ',
 '10/1/24, 12:16\u202fPM - ',
 '10/1/24, 12:17\u202fPM - ',
 '10/1/24, 12:17\u202fPM - ',
 '10/1/24, 12:18\u202fPM - ',
 '10/1/24, 12:18\u202fPM - ',
 '10/1/24, 12:22\u202fPM - ',
 '10/1/24, 12:23\u202fPM - ',
 '10/1/24, 12:23\u202fPM - ',
 '10/1/24, 12:24\u202fPM - ',
 '10/1/24, 12:26\u202fPM - ',
 '10/1/24, 12:34\u202fPM - ',
 '10/1/24, 1:21\u202fPM - ',
 '10/1/24, 1:24\u202fPM - ',
 '10/1/24, 8:05\u202fPM - ',
 '10/1/24, 8:06\u202fPM - ',
 '10/1/24, 8:19\u202fPM - ',
 '10/1/24, 8:19\u202fPM - ',
 '10/1/24, 8:19\u202fPM - ',
 '10/2/24, 12:04\u202fAM - ',
 '10/2/24, 12:06\u202fAM - ',
 '10/2/24, 12:07\u202fAM - ',
 '10/2/24, 12:07\u202fAM - ',
 '10/2/24, 12:07\u202fAM - ',
 '10/2/24, 12:14\u202fAM - ',
 '10/2/24, 12:22\u202fAM - ',
 '10/2/24, 12:25\u202fAM - ',
 '10/2/24, 12:25\u202fAM - ',
 '10/2/24, 12:27\u202fAM - ',
 '10/2/24, 12:29\u202fAM - ',
 '10/2/24, 12:29\u202fAM - ',
 '10/2/24, 12:31\u202fAM - ',
 '10/2/24, 12:35\u202fAM - ',
 '10/2/24, 12:39\u202fAM - ',
 '10/2/24, 12:40\u202fAM - ',
 '10/2/24, 12:42\u202fAM - ',
 '10/2/24, 1:19\u202fAM - ',
 '10/2/24, 1:19\u202fAM - ',
 '10/2/24, 1:26\u202fAM - ',
 '10/2/24, 1:33\u202fAM - ',
 '10/2/24, 1:34\u202fAM - ',
 '10/2/24, 1:35\u202fAM - ',
 '10/2/24, 1:39\u202fAM - ',
 '10/2/24, 7:02\u202fAM - ',
 '10/2/24, 7:10\u202fAM - ',
 '10/2/24, 9:03\u202fAM - ',
 '10/2/24, 9:07\u202fAM - ',
 '10/2/24, 9:13\u202fAM - ',
 '10/2/24, 11:03\u202fAM - ',
 '10/2/24, 11:20\u202fAM - ',
 '10/2/24, 12:15\u202fPM - ',
 '10/2/24, 12:25\u202fPM - ',
 '10/2/24, 12:25\u202fPM - ',
 '10/2/24, 6:31\u202fPM - ',
 '10/2/24, 6:31\u202fPM - ',
 '10/2/24, 6:59\u202fPM - ',
 '10/2/24, 6:59\u202fPM - ',
 '10/2/24, 11:02\u202fPM - ',
 '10/2/24, 11:02\u202fPM - ',
 '10/2/24, 11:24\u202fPM - ',
 '10/2/24, 11:24\u202fPM - ',
 '10/3/24, 2:21\u202fAM - ',
 '10/3/24, 2:24\u202fAM - ',
 '10/3/24, 2:57\u202fAM - ',
 '10/3/24, 6:07\u202fAM - ',
 '10/3/24, 10:47\u202fAM - ',
 '10/3/24, 10:57\u202fAM - ',
 '10/3/24, 11:08\u202fAM - ',
 '10/3/24, 11:53\u202fAM - ',
 '10/3/24, 11:54\u202fAM - ',
 '10/3/24, 3:12\u202fPM - ',
 '10/3/24, 3:12\u202fPM - ',
 '10/3/24, 3:12\u202fPM - ',
 '10/3/24, 3:13\u202fPM - ',
 '10/3/24, 3:13\u202fPM - ',
 '10/3/24, 3:15\u202fPM - ',
 '10/3/24, 3:16\u202fPM - ',
 '10/3/24, 3:16\u202fPM - ',
 '10/3/24, 3:24\u202fPM - ',
 '10/3/24, 3:25\u202fPM - ',
 '10/3/24, 3:25\u202fPM - ',
 '10/3/24, 3:25\u202fPM - ',
 '10/3/24, 3:25\u202fPM - ',
 '10/3/24, 3:26\u202fPM - ',
 '10/3/24, 3:26\u202fPM - ',
 '10/3/24, 3:35\u202fPM - ',
 '10/3/24, 3:36\u202fPM - ',
 '10/3/24, 3:49\u202fPM - ',
 '10/3/24, 10:24\u202fPM - ',
 '10/3/24, 10:24\u202fPM - ',
 '10/3/24, 10:25\u202fPM - ',
 '10/3/24, 10:42\u202fPM - ',
 '10/3/24, 10:43\u202fPM - ',
 '10/3/24, 11:02\u202fPM - ',
 '10/3/24, 11:05\u202fPM - ',
 '10/4/24, 6:58\u202fAM - ',
 '10/4/24, 7:17\u202fAM - ',
 '10/4/24, 2:06\u202fPM - ',
 '10/4/24, 5:05\u202fPM - ',
 '10/4/24, 5:06\u202fPM - ',
 '10/4/24, 6:10\u202fPM - ',
 '10/4/24, 9:35\u202fPM - ',
 '10/4/24, 9:35\u202fPM - ',
 '10/5/24, 1:58\u202fPM - ',
 '10/23/24, 10:39\u202fPM - ',
 '10/25/24, 11:48\u202fPM - ',
 '10/29/24, 1:46\u202fPM - ',
 '10/29/24, 1:47\u202fPM - ',
 '10/29/24, 1:52\u202fPM - ',
 '10/29/24, 1:52\u202fPM - ',
 '10/29/24, 1:56\u202fPM - ',
 '10/29/24, 1:59\u202fPM - ',
 '10/29/24, 1:59\u202fPM - ',
 '10/29/24, 1:59\u202fPM - ',
 '10/29/24, 2:00\u202fPM - ',
 '10/29/24, 2:11\u202fPM - ',
 '10/29/24, 2:42\u202fPM - ',
 '10/29/24, 2:50\u202fPM - ',
 '10/29/24, 2:51\u202fPM - ',
 '10/29/24, 2:56\u202fPM - ',
 '10/29/24, 2:57\u202fPM - ',
 '10/29/24, 3:01\u202fPM - ',
 '10/29/24, 3:03\u202fPM - ',
 '10/29/24, 3:03\u202fPM - ',
 '10/29/24, 3:04\u202fPM - ',
 '10/29/24, 3:04\u202fPM - ',
 '10/29/24, 3:04\u202fPM - ',
 '10/29/24, 3:05\u202fPM - ',
 '10/29/24, 3:05\u202fPM - ',
 '10/29/24, 3:06\u202fPM - ',
 '10/29/24, 3:06\u202fPM - ',
 '10/29/24, 3:27\u202fPM - ',
 '10/29/24, 3:43\u202fPM - ',
 '10/29/24, 3:52\u202fPM - ',
 '12/18/24, 9:45\u202fAM - ',
 '12/20/24, 10:20\u202fPM - ',
 '12/20/24, 10:23\u202fPM - ',
 '12/20/24, 10:32\u202fPM - ',
 '12/20/24, 10:55\u202fPM - ',
 '12/27/24, 1:06\u202fPM - ',
 '12/27/24, 1:08\u202fPM - ',
 '12/27/24, 8:58\u202fPM - ',
 '12/27/24, 8:58\u202fPM - ',
 '12/27/24, 9:08\u202fPM - ',
 '12/27/24, 9:10\u202fPM - ',
 '12/27/24, 9:41\u202fPM - ',
 '12/27/24, 10:08\u202fPM - ',
 '12/28/24, 12:18\u202fPM - ',
 '12/28/24, 12:18\u202fPM - ',
 '12/28/24, 12:19\u202fPM - ',
 '12/28/24, 12:20\u202fPM - ',
 '12/28/24, 2:25\u202fPM - ',
 '1/15/25, 3:35\u202fPM - ',
 '1/15/25, 3:36\u202fPM - ',
 '1/15/25, 3:37\u202fPM - ',
 '1/15/25, 3:38\u202fPM - ',
 '1/15/25, 3:39\u202fPM - ',
 '1/15/25, 3:40\u202fPM - ',
 '1/15/25, 3:40\u202fPM - ',
 '1/15/25, 3:41\u202fPM - ',
 '1/15/25, 3:50\u202fPM - ',
 '1/15/25, 5:44\u202fPM - ',
 '1/15/25, 5:53\u202fPM - ',
 '1/15/25, 6:56\u202fPM - ',
 '1/15/25, 9:49\u202fPM - ',
 '1/15/25, 9:50\u202fPM - ',
 '1/16/25, 10:10\u202fAM - ',
 '1/16/25, 6:58\u202fPM - ',
 '1/16/25, 9:57\u202fPM - ',
 '1/16/25, 9:58\u202fPM - ',
 '1/16/25, 10:08\u202fPM - ',
 '1/16/25, 10:15\u202fPM - ',
 '1/16/25, 10:20\u202fPM - ',
 '1/16/25, 10:20\u202fPM - ',
 '1/16/25, 10:21\u202fPM - ',
 '1/16/25, 10:25\u202fPM - ',
 '1/16/25, 10:26\u202fPM - ',
 '1/16/25, 10:31\u202fPM - ',
 '1/16/25, 10:32\u202fPM - ',
 '1/16/25, 10:34\u202fPM - ',
 '1/16/25, 10:39\u202fPM - ',
 '1/16/25, 10:39\u202fPM - ',
 '1/16/25, 10:44\u202fPM - ',
 '1/16/25, 10:44\u202fPM - ',
 '1/16/25, 10:45\u202fPM - ',
 '1/17/25, 11:41\u202fAM - ',
 '1/17/25, 11:57\u202fAM - ',
 '1/17/25, 11:57\u202fAM - ',
 '1/18/25, 11:52\u202fPM - ',
 '1/19/25, 10:22\u202fAM - ',
 '1/19/25, 4:38\u202fPM - ',
 '1/19/25, 6:17\u202fPM - ',
 '1/19/25, 6:53\u202fPM - ',
 '1/19/25, 6:54\u202fPM - ',
 '1/19/25, 8:07\u202fPM - ',
 '1/19/25, 10:44\u202fPM - ',
 '1/19/25, 10:45\u202fPM - ',
 '1/20/25, 5:21\u202fPM - ',
 '1/20/25, 9:29\u202fPM - ',
 '1/20/25, 9:29\u202fPM - ',
 '1/20/25, 9:47\u202fPM - ',
 '1/20/25, 9:47\u202fPM - ',
 '1/20/25, 10:38\u202fPM - ',
 '1/20/25, 10:39\u202fPM - ',
 '1/20/25, 11:06\u202fPM - ',
 '1/20/25, 11:06\u202fPM - ',
 '1/21/25, 12:15\u202fAM - ',
 '1/21/25, 7:35\u202fAM - ',
 '1/21/25, 10:42\u202fAM - ',
 '1/21/25, 10:42\u202fAM - ',
 '1/21/25, 10:42\u202fAM - ',
 '1/21/25, 9:30\u202fPM - ',
 '1/21/25, 9:31\u202fPM - ',
 '1/21/25, 9:31\u202fPM - ',
 '1/21/25, 9:32\u202fPM - ',
 '1/21/25, 9:32\u202fPM - ',
 '1/21/25, 9:33\u202fPM - ',
 '1/21/25, 9:33\u202fPM - ',
 '1/21/25, 9:34\u202fPM - ',
 '1/21/25, 9:36\u202fPM - ',
 '1/21/25, 9:39\u202fPM - ',
 '1/21/25, 9:41\u202fPM - ',
 '1/21/25, 9:43\u202fPM - ',
 '1/21/25, 9:43\u202fPM - ',
 '1/21/25, 9:46\u202fPM - ',
 '1/21/25, 9:53\u202fPM - ',
 '1/21/25, 10:27\u202fPM - ',
 '1/21/25, 10:32\u202fPM - ',
 '1/21/25, 10:39\u202fPM - ',
 '1/21/25, 11:34\u202fPM - ',
 '1/21/25, 11:40\u202fPM - ',
 '1/22/25, 7:18\u202fAM - ',
 '1/22/25, 12:52\u202fPM - ',
 '1/22/25, 12:54\u202fPM - ',
 '1/22/25, 1:12\u202fPM - ',
 '1/22/25, 2:04\u202fPM - ',
 '1/22/25, 2:07\u202fPM - ',
 '1/22/25, 8:17\u202fPM - ',
 '1/22/25, 8:17\u202fPM - ',
 '1/22/25, 8:18\u202fPM - ',
 '1/22/25, 8:18\u202fPM - ',
 '1/22/25, 8:18\u202fPM - ',
 '1/22/25, 8:23\u202fPM - ',
 '1/22/25, 8:25\u202fPM - ',
 '1/22/25, 8:26\u202fPM - ',
 '1/22/25, 8:28\u202fPM - ',
 '1/22/25, 8:29\u202fPM - ',
 '1/22/25, 8:30\u202fPM - ',
 '1/22/25, 8:30\u202fPM - ',
 '1/22/25, 8:32\u202fPM - ',
 '1/22/25, 9:19\u202fPM - ',
 '1/22/25, 9:36\u202fPM - ',
 '1/22/25, 9:57\u202fPM - ',
 '1/22/25, 10:01\u202fPM - ',
 '1/22/25, 10:02\u202fPM - ',
 '1/22/25, 10:02\u202fPM - ',
 '1/22/25, 10:03\u202fPM - ',
 '1/22/25, 10:03\u202fPM - ',
 '1/22/25, 10:03\u202fPM - ',
 '1/22/25, 10:04\u202fPM - ',
 '1/22/25, 10:04\u202fPM - ',
 '1/22/25, 11:31\u202fPM - ',
 '1/22/25, 11:31\u202fPM - ',
 '1/23/25, 7:51\u202fAM - ',
 '1/23/25, 11:23\u202fAM - ',
 '1/23/25, 11:24\u202fAM - ',
 '1/23/25, 11:35\u202fAM - ',
 '1/23/25, 12:02\u202fPM - ',
 '1/23/25, 12:08\u202fPM - ',
 '1/23/25, 12:09\u202fPM - ',
 '1/23/25, 12:09\u202fPM - ',
 '1/23/25, 12:12\u202fPM - ',
 '1/23/25, 12:13\u202fPM - ',
 '1/23/25, 12:13\u202fPM - ',
 '1/23/25, 12:13\u202fPM - ',
 '1/23/25, 12:14\u202fPM - ',
 '1/23/25, 12:15\u202fPM - ',
 '1/23/25, 12:15\u202fPM - ',
 '1/23/25, 12:16\u202fPM - ',
 '1/23/25, 12:27\u202fPM - ',
 '1/23/25, 12:46\u202fPM - ',
 '1/23/25, 12:50\u202fPM - ',
 '1/23/25, 1:39\u202fPM - ',
 '1/23/25, 1:42\u202fPM - ',
 '1/23/25, 2:08\u202fPM - ',
 '1/23/25, 2:41\u202fPM - ',
 '1/23/25, 2:41\u202fPM - ',
 '1/23/25, 2:42\u202fPM - ',
 '1/23/25, 2:46\u202fPM - ',
 '1/23/25, 7:12\u202fPM - ',
 '1/23/25, 8:29\u202fPM - ',
 '1/23/25, 8:31\u202fPM - ',
 '1/23/25, 8:32\u202fPM - ',
 '1/23/25, 8:42\u202fPM - ',
 '1/23/25, 9:25\u202fPM - ',
 '1/23/25, 9:29\u202fPM - ',
 '1/23/25, 9:30\u202fPM - ',
 '1/23/25, 9:49\u202fPM - ',
 '1/23/25, 10:26\u202fPM - ',
 '1/23/25, 10:47\u202fPM - ',
 '1/23/25, 10:49\u202fPM - ',
 '1/23/25, 10:50\u202fPM - ',
 '1/23/25, 10:52\u202fPM - ',
 '1/23/25, 10:53\u202fPM - ',
 '1/23/25, 10:53\u202fPM - ',
 '1/24/25, 8:41\u202fAM - ',
 '1/24/25, 9:27\u202fAM - ',
 '1/24/25, 9:45\u202fAM - ',
 '1/24/25, 9:45\u202fAM - ',
 '1/24/25, 9:50\u202fAM - ',
 '1/24/25, 10:48\u202fAM - ',
 '1/24/25, 10:56\u202fAM - ',
 '1/24/25, 12:11\u202fPM - ',
 '1/24/25, 12:13\u202fPM - ',
 '1/24/25, 12:14\u202fPM - ',
 '1/24/25, 12:18\u202fPM - ',
 '1/24/25, 12:24\u202fPM - ',
 '1/24/25, 1:33\u202fPM - ',
 '1/24/25, 2:42\u202fPM - ',
 '1/24/25, 2:42\u202fPM - ',
 '1/24/25, 2:43\u202fPM - ',
 '1/24/25, 2:54\u202fPM - ',
 '1/24/25, 3:04\u202fPM - ',
 '1/24/25, 3:05\u202fPM - ',
 '1/24/25, 3:05\u202fPM - ',
 '1/24/25, 4:53\u202fPM - ',
 '1/24/25, 4:53\u202fPM - ',
 '1/24/25, 4:53\u202fPM - ',
 '1/24/25, 5:16\u202fPM - ',
 '1/24/25, 5:16\u202fPM - ',
 '1/24/25, 5:28\u202fPM - ',
 '1/24/25, 5:28\u202fPM - ',
 '1/24/25, 6:11\u202fPM - ',
 '1/24/25, 6:12\u202fPM - ',
 '1/24/25, 6:34\u202fPM - ',
 '1/24/25, 6:36\u202fPM - ',
 '1/24/25, 6:41\u202fPM - ',
 '1/24/25, 6:42\u202fPM - ',
 '1/24/25, 7:37\u202fPM - ',
 '1/24/25, 7:37\u202fPM - ',
 '1/24/25, 8:23\u202fPM - ',
 '1/24/25, 8:23\u202fPM - ',
 '1/24/25, 8:38\u202fPM - ',
 '1/24/25, 8:39\u202fPM - ',
 '1/24/25, 8:44\u202fPM - ',
 '1/24/25, 10:24\u202fPM - ',
 '1/24/25, 10:24\u202fPM - ',
 '1/24/25, 10:24\u202fPM - ',
 '1/24/25, 10:29\u202fPM - ',
 '1/24/25, 10:29\u202fPM - ',
 '1/24/25, 10:29\u202fPM - ',
 '1/24/25, 10:39\u202fPM - ',
 '1/24/25, 10:40\u202fPM - ',
 '1/25/25, 7:48\u202fAM - ',
 '2/6/25, 1:29\u202fPM - ',
 '2/6/25, 1:30\u202fPM - ',
 '2/6/25, 1:31\u202fPM - ',
 '2/6/25, 1:31\u202fPM - ',
 '2/6/25, 1:31\u202fPM - ',
 '2/6/25, 1:33\u202fPM - ',
 '2/6/25, 1:33\u202fPM - ',
 '2/6/25, 1:47\u202fPM - ',
 '2/6/25, 1:50\u202fPM - ',
 '2/6/25, 1:50\u202fPM - ',
 '2/7/25, 11:21\u202fAM - ',
 '2/7/25, 11:35\u202fAM - ']

In [13]:
df=pd.DataFrame({'user_message':messages,"message_date":dates})

df["message_date"] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %I:%M %p - ')

df.rename(columns={'message_date':'date'},inplace=True)

df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. N... 2024-05-26 09:06:00
1  Sayal Singh Sikarwar Bhaiya RMC created group ... 2024-05-25 22:10:00
2  You joined a group via invite in the community... 2024-05-26 09:06:00
3  +91 78773 95130 joined using this group's invi... 2024-05-26 11:04:00
4  Rohan Kaari Room No. 506 joined using this gro... 2024-05-26 16:14:00

In [14]:
df.shape

(682, 2)

In [15]:
df.columns

Index(['user_message', 'date'], dtype='object')

In [16]:
users=[]
messages=[]

for message in df['user_message']:
    entry=re.split('([\w\W]+?):\s',message)
    if entry[1:]:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])

df["user"]=users
df["message"]=messages
df.drop(columns=['user_message'],inplace=True)

df.sample(5)

,date,user,message
314,2024-10-01 12:07:00,Saurav D Praveen Junior RMC Events Domain,OK bhaiya got it.\n
519,2025-01-20 22:39:00,Anjul Kaari Room No. 506,<Media omitted>\n
70,2024-09-04 21:36:00,Satvik Sawhney Bhaiya RMC,Okk\n
600,2025-01-23 14:08:00,Parv Bhawsar RMC Junior Events Domain,"Hello, I will be attending the full event exce..."
494,2025-01-16 22:32:00,Rohit Girish SRM Roommate,"Don't post it in the group , \nWe will be shar..."

In [17]:
df["year"]=df["date"].dt.year

In [18]:
df.head()

,date,user,message,year
0,2024-05-26 09:06:00,group_notification,Messages and calls are end-to-end encrypted. N...,2024
1,2024-05-25 22:10:00,group_notification,Sayal Singh Sikarwar Bhaiya RMC created group ...,2024
2,2024-05-26 09:06:00,You joined a group via invite in the community,RMC'24 Official\n,2024
3,2024-05-26 11:04:00,group_notification,+91 78773 95130 joined using this group's invi...,2024
4,2024-05-26 16:14:00,group_notification,Rohan Kaari Room No. 506 joined using this gro...,2024

In [19]:
df["month"]=df["date"].dt.month_name()

In [20]:
df["day"]=df["date"].dt.day

In [21]:
df["hour"]=df["date"].dt.hour

In [22]:
df["minute"]=df["date"].dt.minute

In [23]:
df.sample(5)

,date,user,message,year,month,day,hour,minute
606,2025-01-23 20:29:00,+91 62052 47989,<Media omitted>\n,2025,January,23,20,29
501,2025-01-17 11:41:00,Kavya Singh,We've only received 4 responses as of now wher...,2025,January,17,11,41
352,2024-10-02 01:19:00,Anjul Kaari Room No. 506,Sukanya from 8 to 5 you are free on 4th oct?\n,2024,October,2,1,19
368,2024-10-02 12:25:00,Kavya Singh,pls join\n,2024,October,2,12,25
513,2025-01-20 17:21:00,Anjul Kaari Room No. 506,❌❌ Reminder ❌❌\nEveryone must join today's mee...,2025,January,20,17,21

In [24]:
!pip install urlextract
from urlextract import URLExtract

extractor=URLExtract()

Requirement already satisfied: urlextract in c:\users\yashv\appdata\local\programs\python\python311\lib\site-packages (1.9.0)
Requirement already satisfied: idna in c:\users\yashv\appdata\local\programs\python\python311\lib\site-packages (from urlextract) (3.10)
Requirement already satisfied: uritools in c:\users\yashv\appdata\local\programs\python\python311\lib\site-packages (from urlextract) (4.0.3)
Requirement already satisfied: platformdirs in c:\users\yashv\appdata\local\programs\python\python311\lib\site-packages (from urlextract) (4.3.6)
Requirement already satisfied: filelock in c:\users\yashv\appdata\local\programs\python\python311\lib\site-packages (from urlextract) (3.18.0)

[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
links=[]

for message in df["message"]:
    links.extend(extractor.find_urls(message))

In [26]:
len(links)

49